import type { Loan, LoansStorageV1 } from "@/lib/types";

/** localStorage key for the loans collection. */
export const LOANS_KEY = "lps_loans_v1";

/** Hard cap on stored loans (pagination-free load + 5MB budget guard). */
export const MAX_LOANS = 200;

/** Validation bounds per SPEC Data Models (Loan). */
export const LOAN_BOUNDS = {
  nameMax: 30,
  principalMin: 1,
  principalMax: 2_000_000_000,
  rateMin: 0,
  rateMax: 30,
  monthsMin: 1,
  monthsMax: 600,
  monthlyMin: 1,
  monthlyMax: 50_000_000,
} as const;

/** Input accepted by createLoan (id/timestamps are generated by the service). */
export type LoanInput = Omit<Loan, "id" | "createdAt" | "updatedAt">;

export function emptyLoansStorage(): LoansStorageV1 {
  return { version: 1, items: [] };
}

/** Minimal structural guard: `{ version: 1, items: Array }`. */
export function isLoansStorageV1(value: unknown): value is LoansStorageV1 {
  if (value == null || typeof value !== "object") return false;
  const v = value as { version?: unknown; items?: unknown };
  return v.version === 1 && Array.isArray(v.items);
}

function isIntInRange(n: unknown, min: number, max: number): boolean {
  return typeof n === "number" && Number.isInteger(n) && n >= min && n <= max;
}

function isFiniteInRange(n: unknown, min: number, max: number): boolean {
  return typeof n === "number" && Number.isFinite(n) && n >= min && n <= max;
}

/** True only when every field satisfies the SPEC bounds. */
export function isValidLoanInput(input: LoanInput): boolean {
  if (input == null || typeof input !== "object") return false;
  const { name, principalRemaining, annualInterestRate, remainingMonths, monthlyPayment } = input;
  if (typeof name !== "string") return false;
  if (name.trim().length < 1 || name.length > LOAN_BOUNDS.nameMax) return false;
  if (!isIntInRange(principalRemaining, LOAN_BOUNDS.principalMin, LOAN_BOUNDS.principalMax)) return false;
  if (!isFiniteInRange(annualInterestRate, LOAN_BOUNDS.rateMin, LOAN_BOUNDS.rateMax)) return false;
  if (!isIntInRange(remainingMonths, LOAN_BOUNDS.monthsMin, LOAN_BOUNDS.monthsMax)) return false;
  if (!isIntInRange(monthlyPayment, LOAN_BOUNDS.monthlyMin, LOAN_BOUNDS.monthlyMax)) return false;
  return true;
}
